import type { Metadata } from "next";
// @ts-ignore: no type declarations for side-effect import of './globals.css'
import "./globals.css";

export const metadata: Metadata = {
  title: "Mansur Mohammed Bala",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">{children}</body>
    </html>
  );
}
